# Introduction

Uncovering the mechanisms behind environmentally responsive mutagenesis informs our understanding of evolution, notably antimicrobial resistance, where mutation supply can be critical [@Gifford2023; @Ragheb2019]. Microbial mutation rates are responsive to a wide variety of environmental factors including population density [@Krasovec2017], temperature [@Chu2018], growth rate [@Maharjan2018; @Liu2019], stress [@MacLean2013; @Foster2007], growth phase [@Loewe2003] and nutritional state [@Maharjan2017]. Such mutation rate plasticity inspires the idea of "anti-evolution drugs", able to slow the evolution of antimicrobial resistance during the treatment of an infection [@Ragheb2019; @Cirz2005; @Domenech2020; @Alam2016]. Even small reductions in the mutation rate (2-5-fold) can have dramatic effects on the capacity of bacterial populations to adapt to antibiotic treatment, particularly when evolution is limited by mutation supply, as is the case for small pathogen populations [@Ragheb2019].

Microbial mutation rates have an inverse association with population density across all domains of life, we have previously shown that 93% of otherwise unexplained variation in published mutation rate estimates is explained by the final population density [@Krasovec2017]. This density-associated mutation rate plasticity (DAMP) is a distinct phenotype from stress-induced mutagenesis, which acts via independent genetic mechanisms [@Krasovec2018]. Population density alters not only the rate but also the spectrum of mutations, with significantly higher rates of AT\>GC transitions seen in low density populations [@Gifford2023]. Density effects are likely relevant to natural populations given that population sizes and densities vary greatly, for example, *Escherichia coli* populations in host faeces can range in density by 5 orders of magnitude ([**16**](https://www.biorxiv.org/content/10.1101/2023.09.27.557722v1.full#ref-16)), and infections can be established by populations as small as 6×10^3^ cells ([**17**](https://www.biorxiv.org/content/10.1101/2023.09.27.557722v1.full#ref-17)). We therefore aim to mechanistically describe the widespread phenotype of DAMP.

In order to test potential mechanisms generating DAMP, we developed and systematically assessed a computational model connecting metabolism and mutagenesis in a growing *E. coli* population. This model generates the hypothesis that the key determinants of DAMP are the production and degradation rates of reactive oxygen species (ROS). Though molecular oxygen is relatively stable it can be reduced to superoxide (^•^O~2−~), hydrogen peroxide (H~2~O~2~) and hydroxyl radicals (HO^•^). These "reactive oxygen species" are strong oxidants able to damage multiple biological molecules including nucleotides and DNA ([**18**](https://www.biorxiv.org/content/10.1101/2023.09.27.557722v1.full#ref-18)). We tested the role of ROS in controlling DAMP by estimating mutation rate plasticity under different conditions of environmental oxygen and with genetic manipulations known to alter ROS dynamics. We find that the reduction in mutation rate at increased population density results from the population's increased ability to degrade H~2~O~2~, resulting in reduced ROS-associated mutagenesis. We show that this density effect is also experienced by cells deficient in H~2~O~2~ degradation when cocultured with wild-type cells able to detoxify the environment. Mutation rates therefore depend not only on the genotype of the individual but also on the community's capacity to degrade H~2~O~2~.
